### ISSUE TITLE
Raspberry Pi issue

### ISSUE THREAD

**Issue by rapidnine** [markop159/KODI-Popcorn-Time#14]
Hello.

I own a 1st gen Raspberry Pi and I can't make this addon work on it.

The download goes perfectly, I can search whatever I want but as soon as I try to play something nothing happens. A progress bar pops up and disappears immediately.

I tried OSMC and LibreElec.

Is there any solution? Thanks.

**Edit: [I just noticed someone had the exact same problem with the original fork](https://github.com/Diblo/KODI-Popcorn-Time/issues/101)**

**Comment by markop159** [comment]
Can you provide logs so I can check what goes wrong, maybe we can fix it. I own rpi2 and is working great, maybe torrent engine used in this addon cannot work on first rpi.

**Comment by rapidnine** [comment]
I hope we can find something (I couldn't upload on Pastebin due to the size).

http://paste.osmc.io/raw/efemaheces

**Comment by markop159** [comment]
I checked logs and problem is with missing armv6 binaries for torrent2http, I found binaries that should work with 1st gen RPI (armv6). Can you please try this test build before I update release version with these binaries. Just install as a zip file.

[ARMv6 Test Build](https://github.com/markop159/KODI-Popcorn-Time/blob/master/test_builds/plugin.video.kodipopcorntime-1.5.4.rc2.test.zip?raw=true)

**Comment by rapidnine** [comment]
Thanks, I just installed the build on my RasPi but this time KODI Popcorn Time won't launch at all.

I reproduced the issue and uploaded the log file.
 [kodi.log](https://github.com/markop159/KODI-Popcorn-Time/files/491656/kodi.log.zip)

**Comment by markop159** [comment]
Hi I think I had a typo in code, can you redownload test build and try again.

It is hard to do it this way but I cannot test it because I do not own a 1st gen, so I hope we can fix this issue with your help.

**Comment by pbouthil** [comment]
Update from: New Kodi Popcorn Time 1.0.1.b Release not streaming on Raspberry Pi B+ w/LibreELEC 7.0.2 #101

I have tried the new version of Popcorn Time for Kodi (1.5.4rc2) on both my RPi B+ and RPi3 with different results. The RPi B+ still acts the same as before (pop up opens and immediately closes). The RPi3 when selecting a movie to stream had a pop up window that says "Fetching Stream" and stays like that until you cancel out of the window minutes later.

**Comment by markop159** [comment]
@pbouthil can you provide some logs? On your 1st gen RPI did you try test armv6 build or general build?

**Comment by pbouthil** [comment]
Marko,

I don’t have a Gen1 Pi I have a RPi B+ (armv6)and RPi3 (armv7) and neither of them work with Popcorn Time Kodi. Is there any dependencies that are out dated that might be causing issues? I looked for logs but didn’t find any on the SD card. I tried the armv6 build that you provided.

**Comment by markop159** [comment]
@pbouthil, [here](https://github.com/markop159/KODI-Popcorn-Time/wiki/Discussions%2C-Proposals%2C-Issues-and-Bugs) you can read how to turn on debugging in kodi and where to find a log file. Without log file I cannot do anything because I do not own an RPI B+ or RPI 3, but colege of mine have the RPI 3 and for him it is working fine.

**Comment by pbouthil** [comment]
Marko,


Thanks for the info. I will turn on the debugging tool and see what that does. Where does your college live? Maybe it is the location that is problem. Is your college using OpenELEC or LibreELEC? FYI... I am using a VPN  with Popcorn Time and accessing a server in Germany.


Paul P. Bouthillier


________________________________

**Comment by markop159** [comment]
Paul

Can you try using official [Popcorn Time](https://popcorntime.sh) aplication trought your VPN provider (to check if it is blocking some trackers or P2P trafic)?

We are using OSMC on our RPIs and are not using any VPN provider (not yet needed to in our country) :)

**Comment by pbouthil** [comment]
Marko,

I have used the official updated version of Popcorn Time on my RPI3 and used the test version that you attached to Github on my RPI B+. Both using my VPN client. Do you think that it could be that there could be differences between OSMC and OpenELEC/LibreELEC? I have not yet tried OSMC on my RPI’s. Do you have the capacity to try installing LibreELEC on your RPI’s and testing it? On my end I will try installing OSMC on my RPI B+ and test it out.

**Comment by markop159** [comment]
@pbouthil, @rapidnine 

Can you please try new build 1.5.5.rc3 I incorporated armv6 binaries. I found out that one of my friends have an RPI B+ device without using VPN and installed LibreELEC, and we tested the latest build with armv6 binaries and was working preaty OK. You have to set to 720p or lower setting because it seems 1080p is a little bit too much for armv6 RPI. Fetching info can take a lot of time (from 5 to 10 minutes).

**Comment by pbouthil** [comment]
I will give it a try next weekend. I am out of town next week.

**Comment by pbouthil** [comment]
Marko,

I actually found some time to try out your new version on both my RPI B+ and RPI3. I still have the same issue. I tried it with my VPN connected. I will try with no VPN to see if that makes a difference. I will keep you informed.

**Comment by markop159** [comment]
Tnx for trying. Before you try without VPN can you try downloading some torrent using VPN to see If it is working.

**Comment by markop159** [comment]
@rapidnine , @pbouthil any news?

**Comment by andriuski** [comment]
@markop159  just tried the latest version on my B+, still no luck. It is not a network issue as same addon same settings same network works fine on android tablet.

Andrius

**Comment by markop159** [comment]
@andriuski you can get the log using [this](https://github.com/markop159/KODI-Popcorn-Time/wiki/Discussions%2C-Proposals%2C-Issues-and-Bugs).

**Comment by andriuski** [comment]
@markop159 I will post it in 12 hours.

**Comment by andriuski** [comment]
@markop159 my log is here [http://pastebin.com/xqJ6Aacz](url)

**Comment by pbouthil** [comment]
Marko,

Sorry for the delay I was out of town on business trip. It still won’t  work on both my B+ and RPI3

**Comment by markop159** [comment]
@andriuski Thnx for log, I guess the ARMv6 version of RPI is a bit slow so I removed the timeout check for loading binaries and created a test build specifically for ARMv6 to check if it is loading the correct binaries. This build does not contain binaries for other systems. Install it as a ZIP file and post the log file.

https://github.com/markop159/KODI-Popcorn-Time/blob/master/test_builds/plugin.video.kodipopcorntime.ARMv6.zip?raw=true

**Comment by andriuski** [comment]
@markop159 will try to get the logs back to you in 8 hours.
Also, does the plugin work on PI2 or PI3? I'm thinking about an upgrade eventually.

**Comment by markop159** [comment]
@andriuski yes plugin is working on RPI2 (using myself with OSMC installed) and RPI3.

**Comment by andriuski** [comment]
@markop159 still no luck with armv6 version. [Log is here](https://paste.ubuntu.com/23319068/)

**Comment by markop159** [comment]
@andriuski It seems that there is a problem with detecting if it is ARMv6 or ARMv7, I made some changes please try 2nd ARMv6 build:

https://github.com/markop159/KODI-Popcorn-Time/blob/master/test_builds/plugin.video.kodipopcorntime.ARMv6-2.zip?raw=true

**Comment by andriuski** [comment]
@markop159,

Good news, but I need to explain the process so you know whats in the logs.
I installed the ARMv6-2 and restarted my PI. Ran the addon. Everything went OK up until I opened Most watched (movies) and the progress indicator for fetching information appeared. It wen't all the way to 100% and then just closed. That was it. I tried once again and the result was the same.
[Log is here](https://paste.ubuntu.com/23321843/)
Then I've restarted the PI and tried once more. This time i got all the way to the list of movies. Clicked on one and nothing. Tried a different one and it fetched info and started playing.
[Log is here](https://paste.ubuntu.com/23321926/)

I will tray it again a few times today and let you know.

Andrius

**Comment by markop159** [comment]
@andriuski Thnx for your cooperation, I am glad it is finally working (at least partially) on ARMv6 based RPI. Can you please try to enable debugging in "KODI Popcorn Time" settings and enable "debugging" in KODI: "Settings -> System -> Logging" toggle the "Enable debug logging" setting.

After you enable all this make some test and post logs so I can see what is going on.

**Comment by andriuski** [comment]
@markop159 as requested, the log with debugging info.
I appreciate the work you do, but the slowness of the addon on RP is killing me.

[kodi.zip](https://github.com/markop159/KODI-Popcorn-Time/files/529805/kodi.zip)

**Comment by markop159** [comment]
@andriuski I am glad I can make my plugin work on most devices that are running KODI but I know that RPI1 is kinda slow and looking at log I see it has problems with multi threading.

So if you are looking for the upgrade, I would recomend you RPI3 because it is faster than RPI2 and has integrated wi-fi and BT. This plugin is working a lot better on RPI3 than on 1st and 2nd RPI...

**Comment by pbouthil** [comment]
Marko,


I am going to try an experiment by installing Android onto my RPI3 and install Popcorn Time and see if that works. If that does then there has got to be a conflict with either the Raspberry Pi OS or Kodi itself.


Paul P. Bouthillier


________________________________

**Comment by pbouthil** [comment]
Marko,

I finally got to install Android on the RPI3 with Popcorn Time and I was able to download but not stream. I could not get passed the VPN warning the Popcorn Time flags when trying to stream. Even when unchecking the VPN check. I did use my own VPN on the test.

Get Outlook for Android<https://aka.ms/ghei36>



On Sat, Oct 15, 2016 at 2:08 AM -0600, "Marko" <notifications@github.com<mailto:notifications@github.com>> wrote:


@andriuski<https://github.com/andriuski> I am glad I can make my plugin work on most devices that are running KODI but I know that RPI1 is kinda slow and looking at log I see it has problems with multi threading.

So if you are looking for the upgrade, I would recomend you RPI3 because it is faster than RPI2 and has integrated wi-fi and BT. This plugin is working a lot better on RPI3 than on 1st and 2nd RPI...

-

**Comment by markop159** [comment]
@pbouthil if I understand you, you are trying to use official app on android and not the KODI addon. I am not working on the official app. In this case file an issue to the developer of the official popcorn time app.

In case you are trying my addon please add logs. Without logs I cannot fix issues because I cannot reproduce all issues on my end.

**Comment by pbouthil** [comment]
Marko,

I guess I did not explain clearly what I was doing. I was going to try and experiment with my RPI3 by installing Android on it and seeing if Popcorn time would work and the results were that I can download a movie and play it but I can’t directly stream the movie at all because I get the “It is recommended to connect VPN”  notice and I can’t get passed that no matter what I do. I was only trying to see if Kodi or the RPI3 architecture was the issue.

Can you please supply me the info again to activate logs so I can pull them for you…thx

**Comment by kidburglar** [comment]
Hello, I think it's related to this subject.
I have the same probleme, torrent2http not start in kodi.log but if I try to run manually torrent2http on my pi it don't work.

`
runtime: this CPU has no VFPv3 floating point hardware, so it cannot run
this GOARM=7 binary. Recompile using GOARM=5.
`

I will well try to compile it manually but after few times I not understand how to do it.

**Comment by markop159** [comment]
I found already recompiled binaries so I have never compiled it myself. You can try using testing build that is using armv6 binaries:

https://github.com/markop159/KODI-Popcorn-Time/blob/master/test_builds/plugin.video.kodipopcorntime.ARMv6-2.zip?raw=true

**Comment by kidburglar** [comment]
I don't saw the testing build sorry.
It look better seem if I have another error now.

https://zerobin.net/?f77d8a678ccfcaa2#g/Ft6J+HMDb5rcUZmrCsYbU66528NVHLIOZSpAOXLm8=

**Comment by markop159** [comment]
What device are you using for this? If it is RPI 1 try to reboot RPI, rerun addon multiple times...

As RPI 1 has a slow armv6 CPU this addon does not work ok on it (it can take a lot of time just to show the list of movies and you cannot play 1080p video fluently) I would recommend you to buy a RPI 2 or RPI 3.

**Comment by kidburglar** [comment]
It's a pretty old RPI 1 ^^ (I receive it from a friend). 
A reboot seem working for TV show and Movies (if I search manually).

It look like I missed something because I ask for only French video but I have something in English (maybe I need to restart again, I will try it later).

Thanks for you help anycase the testing build help for torrent2http ^^

**Comment by markop159** [comment]
Version 1.6.2 has added support for ARMv6 device (RPI1 and RPI Zero)

**Comment by pbouthil** [comment]
Marko,

You can close this but FYI I still was unable to get Popcorn Time to work on either my RPi1 or RPi3. I have moved on to using Exodus instead.

**Comment by markop159** [comment]
@pboutil I am sory that this addon never worked for you, but the initial issue (not working on ARMv6) was solved and you never provided any logs so I could not find out where is your problem.
