### ISSUE TITLE
Videos are not played anymore

### ISSUE THREAD

**Issue by mariocosme** [markop159/KODI-Popcorn-Time#15]
Steps to reproduce:
- Open Addon
- TV Shows
- Popular
- Mr. Robot (or any other)
- Select season
- Select episode

Dialog will appear and nothing happens.
Tried in Raspberry Pi3, Windows 10 and MacOS.

You can find a debug log (MacOS) attached.

[kodi.log.zip](https://github.com/markop159/KODI-Popcorn-Time/files/489506/kodi.log.zip)

**Comment by markop159** [comment]
Hi thnx for logs, but I cannot reproduce your problem on my end. I tried Raspberry PI 2 (OSMC); Windows 10; Mac OS X 10.11.

I tried playing movies, TV shows, anime, everything seems it is working fine. Can you check if you have some problems in your network, or can you try just reboot your device (I had once similar problem on Mac OS X and when i rebooted, it started working fine).

**Comment by mariocosme** [comment]
No network or device problems I know of. Reinstalled Kodi, Repository and Addon, rebooted devices and problem still remains. I am also using Google's Public DNS fyi.

**Comment by markop159** [comment]
@mariocosme videos still not playable, or is this issue resolved?

**Comment by juanma-cvega** [comment]
Hi, I have the same problem here. I try any movie or serie and it doesn't start them. I'm using windows 10 in my case. If I enable keeping downloaded files, I can see the video file in the path specify but Kodi doesn't start any of them.

**Comment by markop159** [comment]
Hi @juanma-cvega can you please attach debug log. For me this addon still works like a charm.

**Comment by juanma-cvega** [comment]
Here. Thanks.


[kodi.zip](https://github.com/markop159/KODI-Popcorn-Time/files/546557/kodi.zip)

**Comment by markop159** [comment]
Can you please provide log with debugging enabled in kodi and addon settings. You can find how to do this in projects wiki.

**Comment by juanma-cvega** [comment]
Sorry, I forgot to enable them.
Here.
[kodi.zip](https://github.com/markop159/KODI-Popcorn-Time/files/546605/kodi.zip)

**Comment by markop159** [comment]
Hello @juanma-cvega  tnx for debug log, I can see that torrents start downloading normally (so this part is working fine), then when it should start playing video crashes, I think it is because of subtitles, can you please try to disable auto subtitle download in addon  settings.

as you can see below after we unzip subtitles torrent shuts down and then all goes wrong:
`22:12:45 T:4832   DEBUG: [plugin.video.kodipopcorntime] (Thread-1) (Download) Store data on location C:\Users\MediaCenter\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.kodipopcorntime\cache\temp.zip
22:12:45 T:4832   DEBUG: [plugin.video.kodipopcorntime] (Thread-1) (Download) Successful stored data at http://www.yifysubtitles.com/subtitle-api/star-trek-beyond-yify-97582.zip
22:12:45 T:4832   DEBUG: [plugin.video.kodipopcorntime] (Thread-1) (Loader) Unzipping
22:12:45 T:10404   DEBUG: [plugin.video.kodipopcorntime] (Torrent) Shutting down log pipe
22:12:45 T:10404   DEBUG: [plugin.video.kodipopcorntime] (Torrent) Shutting down torrent2http`

I get the same error when I enable subtitle downloads on RPI2 OSMC. On Windows 10 subtitles download fine.

If this solves your problem you can try adding subtitles through subtitle plugins (such as opensubtitles).

I was already thinking about integrating opensubtitles instead of yify subs, but sadly I cannot find the time to do this (at this moment I am only able to fix some little things).

**Comment by juanma-cvega** [comment]
Hi,
Yes, disabling the subtitles made it work again. I'm also using windows 10 by the way so I don't know why it fails for me. I set up the download path to a network drive even though I have disabled keeping files. I don't know if subtitles are downloaded in the same path.

Thanks!

**Comment by markop159** [comment]
I am glad it is working again for you.

I will try to incorporate downloading subtitles from opensubtitles sometime in the future. Until then please do not use this feature in addon (use external plugin for subtitles).

**Comment by juanma-cvega** [comment]
Hi,
Yes, that fixed the problem. I'll leave subtitles disabled for now then.
Thanks!

**Comment by tmpegoraro** [comment]
Hello, unfortunately my problem has not been resolved. I disabled the subtitles the control panel of the popcorn I restarted the device and still it did not advance.

I use AppleTV 4 with kodi 17.0 Beta3
Can someone help me?

**Comment by tmpegoraro** [comment]
Follow my log, if anyone can help me I appreciate it.

[logkodiAppleTV.txt](https://github.com/markop159/KODI-Popcorn-Time/files/590703/logkodiAppleTV.txt)

**Comment by markop159** [comment]
Hi thnx for trying my addon, but unfortunately I think that this addon will not work on AppleTV because the binaries for torrent2http are not compatible with it. Currently there are integrated binaries for Windows, linux-x86, linux-armv7, android and macOS. There is a test build with binaries for linux-armv6 (RPI 1).

If there is someone who can compile binaries for appleTV I can try to integrate them into my addon but until then unfortunately I cannot help you.

**Comment by tmpegoraro** [comment]
Thanks for the info. @markop159. Is there anything I can help? Your program is really cool, could try to compile for AppleTV, please?
