### ISSUE TITLE
Change Video Source

### ISSUE THREAD

**Issue by joseska** [markop159/KODI-Popcorn-Time#30]
Hi. Is there a simple way to change source video?

I think it´s https://yts.ag/ now......

Thanks....

**Comment by markop159** [comment]
On this version the official popcorntime provider is used, because official provider has movies, series and anime. First version was using yts.ag but it provides only movies and the API had some problems with sorting so I switched to official API provider.

If you want to try you just need modify in this file: "plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/settings/movies.py"

These 2 lines:

            #cls.provider = load_provider('movies_yify')
            cls.provider = load_provider('api-fetch')

so it looks like this:

            cls.provider = load_provider('movies_yify')
            #cls.provider = load_provider('api-fetch')

If it does not work attach logs and if I will have time I will look at it but in generally I will not support yts.ag as a provider.

**Comment by markop159** [comment]
yts.ag is no longer supported in this version of plugin.
