### ISSUE TITLE
TorrentError: Can't start torrent2http

### ISSUE THREAD

**Issue by ivangotoy** [markop159/KODI-Popcorn-Time#68]
Unable to use this addon. Running x86_64 Ubuntu 17.04 with kodi 17.
That's the log I have:
http://pastebin.com/HBc8w06w

**Comment by markop159** [comment]
As I see this, the problem is when addon tries to connect to Torrent2http on localhost, it gets the connection refused:
`23:10:52.884 T:140600250726144   DEBUG: [plugin.video.kodipopcorntime] (Thread-1) (URL) Trying to obtaining data from http://127.0.0.1:5001/status
23:10:52.886 T:140600250726144  NOTICE: [plugin.video.kodipopcorntime] (Thread-1) (Torrent) error: [Errno 111] Connection refused`

I have seen this error on Mac after update to MacOS 12. Then I disabled Firewall on this machine and it started to work. Can you check if you have firewall enabled on your Ubuntu machine. Try to disable it. If this works you can try to disable firewall only on localhost.

**Comment by aleskandro** [comment]
Same issue, iptables is configured with the default policy Accept on all the three chains.

Distro: XBian Jessie
