### ISSUE TITLE
Don't charge torrent files on enigma 2.

### ISSUE THREAD

**Issue by goroldi** [markop159/KODI-Popcorn-Time#99]
Hi, I have installed popcorn time in Kodi on enigma 2 deco and it's not working. It seems that don't find torrent files.
Any idea how to configure it?
Thanks in advance.

**Comment by markop159** [comment]
add logs.

**Comment by goroldi** [comment]
How I can add logs?
In the screen appears fetching information.
And it stopped there.

**Comment by markop159** [comment]
Here you can read how to enable debug logging and log location:
https://github.com/markop159/KODI-Popcorn-Time/wiki/Discussions%2C-Proposals%2C-Issues-and-Bugs

**Comment by goroldi** [comment]
Thanks!!, I don´t know how, but now is working.
even thought I got a lot of errors.

I atthacht the log file in Paste Bin link.

[https://pastebin.com/EBFMJcAq](url)

Thanks a Million for this amazing APP

**Comment by markop159** [comment]
I am glad that it is working now, there are a lot of errors:

> ERROR: CAESinkALSA - snd_pcm_writei(-32) Broken pipe - trying to recover

this errors are due to some incompatibility between kodi and Enigma OS, but if kodi is working I guess they can be ignored.

Another error if it is mentioned less than 10 times can be ignored:

> NOTICE: [plugin.video.kodipopcorntime] (Thread-1) (Torrent) error: [Errno 111] Connection refused

This is when kodi is waiting for torrent to start downloading.

**Comment by goroldi** [comment]
Thank you again. You are amazing!!
Great job!

**Comment by markop159** [comment]
Resolved
